### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by DM-** [anathema/anathema_3e#4]
http://forum.theonyxpath.com/forum/main-category/exalted/474023-state-of-anathema-for-third-edition/page9

I followed the instructions on the link above, but the build fails @ this point

/XXX/XXX/XXX/XXX/XXX/Exalted/Anathema 3e/anathema_3e/Library_FX/src/main/java/net/sf/anathema/library/fx/cell/ConfigurableListCellFactory.java:3: error: cannot find symbol
import javafx.scene.control.ListCell;

And then about another 100 errors. This is using jdk and java 1.8 on debian

**Comment by rlrutherford** [comment]
Which version of the JDK are you using?

Oracle moved com.sun.javafx.Utils to com.sun.javafx.util.Utils in update
60, so you should be running at least jdk 60 or newer.

Rob

**Comment by DM-** [comment]
I finally got it working, there were other issues.

I was/am using openjdk 1.8, the issue was that openjdk doesnt include javafx.
So I installed openjfx, and that part went fine.
Then it had issues when it tried to do the windows release, it kept saying /dev-dist/windows/binaries/launch4j/bin_linux/windres doesnt exist, so I edited the gradle build to not go through the windows or mac builds.
Then it crashed on the test build, so I -x'd it out.

And now it runs, so you can mark this as closed. Sorry for bothering you :D

**Comment by rlrutherford** [comment]
No problem, glad you were able to resolve the issue.
